repositories:
 - name: ingress-nginx
   url: https://kubernetes.github.io/ingress-nginx

 - name: jenkins
   url:  https://charts.jenkins.io 

releases:

- name: ingress-nginx
  namespace: ingress
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.11.0
  values:
    - helm/ingress/values.yaml

- name: jenkins
  namespace: jenkins
  createNamespace: true
  chart: jenkins/jenkins
  version: 5.4.2
  values:
    - helm/jenkins/values.yaml